on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        name: deploy2nekoweb
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: deploy2nekoweb
              uses: indiefellas/deploy2nekoweb@v4
              with:
                  nekoweb-api-key: ${{ secrets.NEKOWEB_API_TOKEN }}
                  # nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
                  nekoweb-folder: "/cedrus.nekoweb.org/"
                  directory: "public"
