on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        name: deploy2nekoweb
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: deploy2nekoweb
              uses: indiefellas/deploy2nekoweb@main
              with:
                  nekoweb-api-key: ${{ secrets.NEKOWEB_API_TOKEN }}
                  nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
                  nekoweb-domain: "cedrus.nekoweb.org"
                  nekoweb-username: "cedrus"
                  directory: "public"
